version: "3.8"

services:
  web:
    build: .
    ports:
      - "9092:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - elearning-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dblearning
      MYSQL_USER: learning_user
      MYSQL_PASSWORD: learning_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - elearning-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db2
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "9093:80"
    depends_on:
      - db
    networks:
      - elearning-network

volumes:
  mysql_data:

networks:
  prostock-network:
    driver: bridge
